title: c3866s
description: "Cyber Security | Linux | Privacy"
author:
  name: "c3866s"
  url: "https://c3866s.github.io"

baseurl: ""

source: .
destination: ./site
permalink: /:title 
paginate: 5
paginate_path: /blog/page:num

defaults:
  
    scope:
    path: ""
    type: "post"
  values:
    layout: "post"

future: true
plugins :
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

owner : "c3866s"
year : "2022"

remote_theme: tocttou/hacker-blog
