title: c3866s
description: "Cybersec | Privacy | Linux | Cryptography"
author:
  name: "c3866s"
  email: ""
  url: "https://c3866s.github.io"

baseurl: ""

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /blog/page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "c"
year : "2022"

# thanks tocttou for this theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# jekyll serve options
port: 8880 #local server port

#thank you brainfucksec ! <3
#https://brainfucksec.github.io/
