title = "c3866s"
description = "Cyber Security | Privacy | Linux"
baseurl = ""
source = "."
destination = "./_site"
permalink = "/:title"
paginate = 5
paginate_path = "/blog/page:num/"
future = true
plugins = [ "jekyll-seo-tag", "jekyll-paginate", "jekyll-sitemap" ]
owner = "c3866s"
year = "2022"
remote_theme = "tocttou/hacker-blog"
port = 8_880

[author]
name = "c3866s"
email = ""
url = "https://c3866s.github.io"

[[defaults]]
[defaults.scope]
path = ""
type = "posts"

[defaults.values]
layout = "post"
